services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    ports:
      - "8000:8000"

  redis:
    image: redislabs/rejson:latest
    container_name: redis
    ports:
      - "6379:6379"